[package]
name = "mem-flip"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
pretty_assertions = "1.4.1"
ratatui = "0.29.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.147"
